### PR TITLE
s2: Document and test how to peek the stream for skippable blocks

### PR DESCRIPTION
**Pull request by Jille**

### CODE REVIEW

**Comment by Jille** [comment]
The test only passes with https://github.com/klauspost/compress/pull/916 and https://github.com/klauspost/compress/pull/917

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by klauspost** [comment]
```
--- FAIL: TestLeadingSkippableBlock (0.01s)
panic: runtime error: index out of range [1[28](https://github.com/klauspost/compress/actions/runs/7655165170/job/20864289889?pr=918#step:5:29)] with length 128 [recovered]
	panic: runtime error: index out of range [128] with length 128

goroutine 2843 [running]:
testing.tRunner.func1.2({0x84475[40](https://github.com/klauspost/compress/actions/runs/7655165170/job/20864289889?pr=918#step:5:41), 0x90c80e0})
	/opt/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1545 +0x2ab
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1548 +0x[43](https://github.com/klauspost/compress/actions/runs/7655165170/job/20864289889?pr=918#step:5:44)e
panic({0x8[44](https://github.com/klauspost/compress/actions/runs/7655165170/job/20864289889?pr=918#step:5:45)7540, 0x90c80e0})
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/panic.go:914 +0x1ec
github.com/klauspost/compress/s2.(*Reader).SkippableCB(...)
	/home/runner/work/compress/compress/s2/reader.go:1064
github.com/klauspost/compress/s2.TestLeadingSkippableBlock(0x914eff0)
	/home/runner/work/compress/compress/s2/reader_test.go:27 +0x2c9
testing.tRunner(0x914eff0, 0x8493ac4)
	/opt/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1595 +0x120
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1648 +0x3dd
```

@Jille PTAL

**Comment by klauspost** [comment]
I will merge the other two first.

**Pull request merged**
