### PR TITLE
zstd: readme -  more details about benchmarking decompression

### PR DESCRIPTION
**Pull request by WojciechMula**
I don't know what's the source of `enwiki9`. Is it https://dumps.wikimedia.org/?

### CODE REVIEW

**Comment by klauspost** [comment]
@WojciechMula A common benchmark corpus: http://mattmahoney.net/dc/textdata.html

**Comment by klauspost** [comment]
Mostly tests many small matches and entropy coding.

**Comment by klauspost** [comment]
Different test inputs:
https://docs.google.com/spreadsheets/d/1nuNE2nPfuINCZJRMt6wFWhKpToF95I47XjSsc-1rbPQ/edit?usp=sharing

Most can be downloaded from https://files.klauspost.com/compress/

**Comment by WojciechMula** [comment]
> Not super sure how relevant this info is for users, though.

That's fine, I'm not insisting on adding this.

**Pull request closed without merging**
