### PR TITLE
zstd: pooledZipWriter should return Writers to the same pool

### PR DESCRIPTION
**Pull request by mostynb**
This code was previously Get'ing objects from one pool and later Put'ing them to a different pool, so they were never reused.

### CODE REVIEW

**Comment by mostynb** [comment]
Also, `pooledZipReader` seems to be unused because it leaks goroutines- would you be interested in merging something like https://github.com/mostynb/zstdpool-syncpool/blob/main/decoderpool.go ?

**Comment by klauspost** [comment]
@mostynb Nice! Thanks!

I don't want to rely on finalizers. I want to fix it properly, ie have a streaming option that only uses the main goroutine.

**Comment by mostynb** [comment]
> I don't want to rely on finalizers. I want to fix it properly, ie have a streaming option that only uses the main goroutine.

I agree that would be preferable. Is it worth commenting out pooledZipReader in the meantime, since it's unused?

**Comment by klauspost** [comment]
@mostynb It is fine to leave. Thanks for the contribution! I will include it in the release I will do shortly.

**Pull request merged**
