### PR TITLE
Try to adress fixes reported by staticcheck

### PR DESCRIPTION
**Pull request by Jacalz**
I know that this PR is huge, but I have tried to split up the changes in multiple commits to make it more digestible. I understand that some of the removed, unused, functions might be unused by mistake, so let's work together on this and add in any functions that were not meant to be unused.

These are the reports still present. Most of them are either false positives in staticcheck (most of the "is unused" remarks below, except for those in zstd/hash.go which had a comment about being unused) or something that I decided need to be done by someone with knowledge of this codebase. I tried fixing the last one, but it caused the tests to fail and hang unfortunately.
```
/home/jacob/Git/compress/huff0/decompress.go
  (1088, 19)  U1000  func (*Scratch).matches is unused

/home/jacob/Git/compress/huff0/huff0.go
  (259, 19)  U1000  func (*Scratch).minSize is unused

/home/jacob/Git/compress/s2/encode.go
  (402, 19)  SA6002  argument should be pointer-like to avoid allocations
  (655, 18)  SA6002  argument should be pointer-like to avoid allocations
  (734, 17)  SA6002  argument should be pointer-like to avoid allocations
  (819, 17)  SA6002  argument should be pointer-like to avoid allocations

/home/jacob/Git/compress/zstd/enc_best.go
  (100, 3)  SA4004  the surrounding loop is unconditionally terminated

/home/jacob/Git/compress/zstd/enc_better.go
  (92, 3)  SA4004  the surrounding loop is unconditionally terminated

/home/jacob/Git/compress/zstd/enc_dfast.go
  (67, 3)   SA4004  the surrounding loop is unconditionally terminated
  (412, 2)  SA4006  this value of offset2 is never used

/home/jacob/Git/compress/zstd/enc_fast.go
  (59, 3)   SA4004  the surrounding loop is unconditionally terminated
  (377, 2)  SA4006  this value of offset2 is never used
  (598, 4)  SA4006  this value of offset2 is never used

/home/jacob/Git/compress/zstd/hash.go
  (22, 6)  U1000  func hashLen is unused
  (39, 6)  U1000  func hash3 is unused
  (45, 6)  U1000  func hash4 is unused
  (69, 6)  U1000  func hash7 is unused

/home/jacob/Git/compress/zstd/internal/xxhash/xxhash.go
  (29, 2)  U1000  var prime2v is unused
  (30, 2)  U1000  var prime3v is unused
  (31, 2)  U1000  var prime4v is unused
  (32, 2)  U1000  var prime5v is unused

/home/jacob/Git/compress/zstd/seqdec.go
  (262, 5)  S1001  should use copy() instead of a loop

 ✖ 22 problems (22 errors, 0 warnings, 0 ignored)
```

### CODE REVIEW

**Comment by klauspost** [comment]
Don't remove unused stuff. Most of it is there for debugging.

Also stuff like `encodeBlockBetterGo` it is used by non-amd64 platforms, so the check is wrong.

Don't modify xxhash.

**Comment by Jacalz** [comment]
> Don't remove unused stuff. Most of it is there for debugging.
> 
> Also stuff like `encodeBlockBetterGo` it is used by non-amd64 platforms, so the check is wrong.

Sure thing. I’ll have all those changes removed.

> Don't modify xxhash.

I know. I checked upstream and that change has literally been done already (it is in the commit message). https://github.com/cespare/xxhash/commit/fd5c34b71e8ec6a322b55ae01fde54e8edea759a

**Comment by Jacalz** [comment]
I’ll start this from scratch in a new PR instead.

**Comment by klauspost** [comment]
@Jacalz Feel free to update to upstream xxhash, just don't want separate changes.

**Pull request closed without merging**
