### PR TITLE
Fix gzhttp transport response.

### PR DESCRIPTION
**Pull request by DeyiXu**
1. Fix response header Content-Encoding: gzip,zstd but not decompress
2. Server side Content-Encoding is not controlled.
Fix the decompression problem when Content-Encoding appears gzip and zstd at the same time

### CODE REVIEW

**Comment by DeyiXu** [comment]
I am implementing a caching middleware, and during use I found that when saving files locally, gzip data that could not be decompressed appeared.

If the data returned through the gzhttp transport middleware needs to be processed and decompressed gzip a second time.

If it can't solve the data perfectly, then what's the point of this middleware's existence?

**Comment by DeyiXu** [comment]
When accessing an uncertain backend HTTP Server, there is no guarantee that the backend server will fully comply with HTTP standards. There may be some data that does not meet the standards. At this time, the data needs to be processed.

The PR I submitted is to solve this problem.

If there is a problem with my code, please reject my PR and I will continue to improve it.

**Comment by DeyiXu** [comment]
Thanks.

I think the option is feasible.

**Comment by DeyiXu** [comment]
Looking forward to your code.

**Comment by klauspost** [comment]
See #978

**Pull request closed without merging**
